apiVersion: apps/v1
kind: Deployment
metadata:
  name: charity-deployment
  labels:
    app: charityapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: charityapi
  template:
    metadata:
      labels:
        app: charityapi
    spec:
      containers:
      - name: charityapi
        image: eu.gcr.io/cloud-ready-roke-team-3/joe/charityimage:latest
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: db-charity
                optional: false
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: db-host
                optional: false
          - name: DATABASE_PORT 
            value: "5432"
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
                optional: false
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
                optional: false
---       
apiVersion: v1
kind: Service
metadata:
  name: charity-service
spec:
  selector:
    app: charityapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: charity-ingress
  spec:
    ingressClassName: nginx
    rules:
        - http:
            paths:
            - pathType: Prefix
              backend:
                service:
                  name: charity-service
                  port:
                    number: 80
              path: /charities